plugins:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false
